name: MineralBot
version: 2.1.0
main: gg.mineral.bot.bukkit.plugin.MineralBotPlugin
author: Jaiden
description: Mineral Bot Plugin
api: '1.8.9'
depend: [ packetevents, ViaVersion, ViaRewind, ViaBackwards ]

commands:
  mineralbot:
    description: Mineral Bot Command
    permission: mineralbot.admin
    usage: /mineralbot