name: MineralBot
version: 2.0.0
main: gg.mineral.bot.plugin.MineralBotPlugin
author: Jaiden
description: Mineral Bot Plugin
api: '1.8.9'
depend: [ packetevents ]

commands:
  mineralbot:
    description: Mineral Bot Command
    permission: mineralbot.admin
    usage: /mineralbot